version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - socket_be

  socket_be:
    build:
      context: ./socket_be
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "3002:3002"
    environment:
      - EXTERNAL_SERVER_URL=wss://10.32.116.158
      - SOCKET_SERVER_URL=https://10.32.116.158
    volumes:
      - ./socket_be/certs:/app/certs
