version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_FILE: ${ENV_FILE} # tham số build, truyền từ .env ngoài
    container_name: nextjs
    ports:
      - "3000:3000"
    env_file:
      - ${ENV_FILE} # load file env vào container
    networks:
      - appnet

networks:
  appnet:
    external: true
