name: Deploy Next.js to Local Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: SSH into local server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: "100.123.107.82"
          username: ${{ secrets.LOCAL_SSH_USER }}
          key: ${{ secrets.LOCAL_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ndr/nextjs-app/fms-internet

            # Ghi nội dung biến môi trường vào file .env
            echo "${{ secrets.PROD_ENV }}" > .env
            cat .env  # Kiểm tra file

            git clone https://github.com/khoicodedao/fms-internet.git
            npm install --force
            npm run build

            pm2 restart nextjs-app
