name: Deploy Next.js to Local Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: SSH into local server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: "100.123.107.82" # Cập nhật IP Tailscale của máy local
          username: ${{ secrets.LOCAL_SSH_USER }}
          key: ${{ secrets.LOCAL_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ndr/nextjs-app/fms-internet
            git pull origin main
            npm install
            npm run build -- --force
            pm2 restart nextjs-app
