name: Deploy Next.js to Local Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: SSH into local server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: "100.123.107.82"
          username: ${{ secrets.LOCAL_SSH_USER }}
          key: ${{ secrets.LOCAL_SSH_PRIVATE_KEY }}
          script: |
            # Write environment variables to .env file
            echo "${{ secrets.PROD_ENV }}" > .env
            cat .env  # Check if the .env file is correct

            # Configure Git to use HTTPS and the PAT for authentication
            git config --global credential.helper store
            echo "https://github.com:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

            # Perform git pull to update the repository
            git pull origin main

            # Install dependencies and build the project
            npm install --force
            npm run build

            # Restart the application using PM2
            pm2 restart nextjs-app
