name: Deploy Next.js to Local Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: SSH into local server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: "100.123.107.82"
          username: ${{ secrets.LOCAL_SSH_USER }}
          key: ${{ secrets.LOCAL_SSH_PRIVATE_KEY }}
          script: |
            # Chuyển đến đúng thư mục chứa Git repository
            cd /home/ndr/nextjs-app/fms-internet || exit 1  # Thoát nếu thư mục không tồn tại

            # Kiểm tra xem có thư mục .git không
            if [ ! -d ".git" ]; then
              echo "❌ Lỗi: Không tìm thấy Git repository trong /home/ndr/nextjs-app/fms-internet"
              exit 1
            fi

            # Ghi biến môi trường vào file .env
            echo "${{ secrets.PROD_ENV }}" > .env
            cat .env  # Kiểm tra nội dung

            # Thiết lập Git để sử dụng token
            git config --global credential.helper store
            echo "https://github.com:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

            # Cập nhật code mới nhất
            git pull origin main

            # Cài đặt dependencies & build
            npm install --force
            npm run build

            # Khởi động lại ứng dụng với PM2
            pm2 restart nextjs-app
